version: "3"
services:
  oauth2:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - TOKENVERIFICATION_ENABLED=false
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=false

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

networks:
  hmpps:
